---
version: 2.1

executors:
  shomei_executor_small:
    docker:
      - image: cimg/openjdk:17.0
    resource_class: small
    working_directory: ~/project
    environment:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2


  xl_machine_executor:
    machine: #https://circleci.com/developer/machine/image/ubuntu-2204
      image: ubuntu-2204:2022.10.2
    resource_class: xlarge

commands:
  prepare:
    description: "Prepare node"
    steps:
      - checkout
      - restore_cache:
          name: Restoring cached gradle dependencies
          keys:
            - deps-{{ checksum "gradle/versions.gradle" }}-{{ .Branch }}-{{ .Revision }}
            - deps-{{ checksum "gradle/versions.gradle" }}
            - deps-



jobs:
  unitTests:
    executor: shomei_executor_small
    steps:
      - prepare
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          no_output_timeout: 20m
          command: |
            ./gradlew --no-daemon build

  assemble:
    executor: shomei_executor_small
    steps:
      - prepare
      - run:
          name: Assemble
          command: |
            ./gradlew --no-daemon clean compileJava compileTestJava assemble
      - save_cache:
          name: Caching gradle dependencies
          key: deps-{{ checksum "gradle/versions.gradle" }}-{{ .Branch }}-{{ .Revision }}
          paths:
            - .gradle
            - ~/.gradle
      - persist_to_workspace:
          root: ~/project
          paths:
            - ./
      - store_artifacts:
          name: Distribution artifacts
          path: build/distributions
          destination: distributions
          when: always

workflows:
  version: 2
  default:
    jobs:
      - assemble
      - unitTests:
          requires:
            - assemble