name: Java Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.parallel=true -Dorg.gradle.workers.max=2

jobs:
  unit-tests:
    runs-on: ubuntu-20.04
    container:
      image: cimg/openjdk:17.0
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Restore Gradle dependencies cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: deps-{{ hashFiles('gradle/versions.gradle') }}
      - name: Build and run unit tests
        run: |
          ./gradlew --no-daemon build

  assemble:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Build distribution
        run: |
          ./gradlew --no-daemon clean compileJava compileTestJava assemble
      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: deps-{{ hashFiles('gradle/versions.gradle') }}
      - name: Save built artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distribution artifacts
          path: build/distributions/*

workflows:
  build-and-test:
    jobs:
      - assemble
      - unit-tests:
          needs: assemble
